name: DIGITAL_DEPLOY

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@master
      - name: Create .env
        run: |
          echo "NODE_ENV=development" > .env
          echo "MONGO_DB_HOST=mongodb://root:abc123@app-db-container:27017/booking-app?directConnection=true&authSource=admin&retryWrites=true" >> .env
          echo "MONGO_DB_PASSWORD=abc123" >> .env
          echo "REDIS_PASSWORD=abc123" >> .env
          echo "REDIS_HOST=redis://:abc123@auth-db-container:6379" >> .env
          echo "GATEWAY_HOST=http://gateway-container:4000" >> .env
          echo "GATEWAY_PORT=4000" >> .env
          echo "FRONTEND_HOST=http://localhost:3000" >> .env
          echo "USER_SERVICE_PORT=4001" >> .env
          echo "USER_SERVICE_HOST=http://user-service-container:4001" >> .env
          echo "HOUSE_SERVICE_PORT=4002" >> .env
          echo "HOUSE_SERVICE_HOST=http://house-service-container:4002" >> .env
          echo "JWT_ACCESS_TOKEN_SECRET=abc123" >> .env
          echo "JWT_ACCESS_TOKEN_TIME=10s" >> .env
          echo "JWT_REFRESH_TOKEN_SECRET=xyz123" >> .env
          echo "JWT_REFRESH_TOKEN_TIME=30s" >> .env
      - name: Run build
        run: docker-compose up -d
